# Generated by Django 4.2.1 on 2023-08-13 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
