# Generated by Django 4.2.1 on 2023-08-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0002_webpage_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='uid',
        ),
    ]
