# Generated by Django 4.2.1 on 2023-08-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0004_alter_webpage_browser_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='link',
            field=models.CharField(blank=True, default=True, max_length=200),
        ),
    ]
