# Generated by Django 4.2.1 on 2023-08-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0005_webpage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
