# Generated by Django 4.2.1 on 2023-08-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0006_alter_webpage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='webrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webrequest',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webrequest',
            name='isp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webrequest',
            name='region_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
